### ISSUE TITLE
Not found "/usr/sbin/set_irq_affinity_cpulist.sh" shell script

### ISSUE THREAD

**Issue by vtlrazin** [Mellanox/ngc_multinode_perf#104]
Hi,
After installing all required prerequisites on Ubuntu 22.04 I receive the error by executing script **ngc_tcp_test.sh**:

**cannot access '/usr/sbin/set_irq_affinity_cpulist.sh': No such file or directory**

Which component should be installed from Ubuntu inbox packages to fix this issue?

Thanks

**Comment by blochl** [comment]
`mlnx-tools`, which is installed with OFED.
