### ISSUE TITLE
Message sizes flags are not in Readme

### ISSUE THREAD

**Issue by amirancel** [Mellanox/ngc_multinode_perf#55]
This commit is merged:
https://github.com/Mellanox/ngc_multinode_perf/commit/a9a322a4a2a5f87713d2fe8d983603f270e73abb

But Readme doesn't show the new flags.

**Comment by blochl** [comment]
Fixed in e1a3bc8ebbce80fd0103afc5029134e350824b30. Closing. Thanks for the catch!
