### ISSUE TITLE
RDMA tests over DPU SF exists with no output

### ISSUE THREAD

**Issue by RazGavrieli** [Mellanox/ngc_multinode_perf#65]
Prior to commit [c08d5d7220a0c2e9e819b1e809f6e9a2dfdf7238](https://github.com/Mellanox/ngc_multinode_perf/commit/cd3e0e6a9a9bbe7646f636ebeff3cfc5d820ea53) the RDMA test was able to receive DPU-to-DPU over SF MLX device. Now the scripts exists with no output and return code 1. For Host-to-Host over PF the script executes as excepted with no issues. 

![image](https://github.com/Mellanox/ngc_multinode_perf/assets/90526270/e15f1466-69e1-4cbc-8deb-0bf73808fee6)

**Comment by blochl** [comment]
Resolved by #67.
