### ISSUE TITLE
Release tag request

### ISSUE THREAD

**Issue by rafsalas19** [Mellanox/ngc_multinode_perf#76]
Hello,
I'm with Azure's AI/HPC engineering organization and we are currently evaluating this tool to replace our current perf-test loopback checks. We would like to integrate this into our VM health check test suite. 

Would it be possible to have tagged releases for ngc_multinode_perf? We like to manage our dependencies by release tag versions.

**Comment by blochl** [comment]
Hi @rafsalas19 , it is indeed planned. I'll try to expedite it. Thanks.

**Comment by blochl** [comment]
@rafsalas19 , please use this to download the latest stable tag: https://github.com/Mellanox/ngc_multinode_perf?tab=readme-ov-file#download-the-latest-stable-version

We will put stable tags from time to time, when there are major changes, after they were tested.
